// Parse a draw.io-exported SVG's embedded mxGraphModel XML into topology
// ground truth: vertex nodes (with geometry) and edges (source/target).
//
// This is the ground truth the neatness gate (verify-deck.mjs) checks rendered
// geometry against, rather than guessing connections from pixels.
//
// Intentionally regex-based (stdlib only, no XML dependency): the embedded
// model is small, flat, and machine-generated by draw.io.

function unescapeHtml(s) {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#10;/g, '\n')
    .replace(/&amp;/g, '&');
}

function attr(tag, name) {
  const m = tag.match(new RegExp(`${name}="([^"]*)"`));
  return m ? m[1] : undefined;
}

export function extractMxModel(svg) {
  const content = attr(svg, 'content');
  const xml = content !== undefined ? unescapeHtml(content) : svg;
  if (!/<mxGraphModel[\s>]/.test(xml)) {
    throw new Error('no embedded <mxGraphModel> found in SVG');
  }
  return xml;
}

export function parseDrawioSvg(svg) {
  const xml = extractMxModel(svg);
  const nodes = [];
  const edges = [];

  const cellRe = /<mxCell\b([^>]*?)(\/>|>([\s\S]*?)<\/mxCell>)/g;
  let m;
  while ((m = cellRe.exec(xml)) !== null) {
    const open = m[1];
    const inner = m[3] ?? '';
    const id = attr(open, 'id');
    if (id === undefined) continue;

    if (/\bedge="1"/.test(open)) {
      edges.push({
        id,
        source: attr(open, 'source'),
        target: attr(open, 'target'),
      });
      continue;
    }

    if (/\bvertex="1"/.test(open)) {
      const geo = inner.match(/<mxGeometry\b([^>]*)\/?>/);
      const g = geo ? geo[1] : '';
      nodes.push({
        id,
        label: unescapeHtml(attr(open, 'value') ?? ''),
        x: Number(attr(g, 'x') ?? 0),
        y: Number(attr(g, 'y') ?? 0),
        w: Number(attr(g, 'width') ?? 0),
        h: Number(attr(g, 'height') ?? 0),
      });
    }
  }
  return { nodes, edges };
}
